FROM python:3.6-slim-stretch
RUN apt-get update && \
    apt-get -y install libmagic-dev && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/app
COPY . /usr/src/app/
CMD ["venv/bin/gunicorn", "linksight.wsgi", "-c", "deploy/gunicorn.py"]
EXPOSE 8000
